click_trx_encoder:
    _target_: ptls.nn.TrxEncoder
    embeddings_noise: 0.003    
    linear_projection_size: 136
    embeddings:
      cat_id:
        in: 400
        out: 64
      level_0:
        in: 400
        out: 16
      level_1:
        in: 400
        out: 8
      level_2:
        in: 400
        out: 4
      hour:
        in: 25
        out: 16
      weekday:
        in: 8
        out: 4

trx_trx_encoder:
    _target_: ptls.nn.TrxEncoder
    norm_embeddings: false
    embeddings_noise: 0.003    
    linear_projection_size: 136
    embeddings:
      mcc_code:
        in: 350
        out: 64
      currency_rk:
        in: 10
        out: 4
      hour:
        in: 25
        out: 16
      weekday:
        in: 8
        out: 4
    #numeric_values:
    #  transaction_amt: log