geo_trx_encoder: 
          _target_: ptls.nn.TrxEncoder
          embeddings_noise: 0.003
          linear_projection_size: 128
          embeddings: 
              geohash_4: 
                  in: 5000
                  out: 32
              geohash_5:
                  in: 5000
                  out: 32
              geohash_6:
                  in: 5000
                  out: 32

trx_trx_encoder: 
          _target_: ptls.nn.TrxEncoder
          embeddings_noise: 0.003
          linear_projection_size: 128
          embeddings:
            event_type:
              in: 58
              out: 24
            event_subtype:
              in: 59
              out: 24
            src_type11:
              in: 85
              out: 24
            src_type12:
              in: 349
              out: 24
            dst_type11:
              in: 84
              out: 24
            dst_type12:
              in: 417
              out: 12
            src_type22:
              in: 90
              out: 24
            src_type32:
              in: 91
              out: 24          
          #numeric_values:
          #  amount: log